# Generated by Django 3.2.9 on 2022-01-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('roll', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('dept', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='app2.customer'),
        ),
    ]
